name: Epic-cicd-dev CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - .gitignore
    tags-ignore:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      archive_artifacts: true
